// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogList: typeof import('./components/BlogList.vue')['default']
    FlipImage: typeof import('./components/FlipImage.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    Links: typeof import('./components/Links.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Nutshell: typeof import('./components/Nutshell.vue')['default']
    OhCV: typeof import('./components/icons/OhCV.vue')['default']
    OhVueIcons: typeof import('./components/icons/OhVueIcons.vue')['default']
    Project: typeof import('./components/Project.vue')['default']
    ProjectList: typeof import('./components/ProjectList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
