// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogList: typeof import('./components/BlogList.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    OhCV: typeof import('./components/icons/OhCV.vue')['default']
    OhVueIcons: typeof import('./components/icons/OhVueIcons.vue')['default']
    ProjectList: typeof import('./components/ProjectList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Socials: typeof import('./components/Socials.vue')['default']
  }
}

export {}
